server:
  port: 9090
  servlet:
    context-path: /csms
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  datasource:
    dynamic:
      primary: db1
      datasource:
        db2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.0.200:3306/hb_csms?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT&allowPublicKeyRetrieval=true
          username: root
          password: 12345678
          # 下面为连接池的补充设置，应用到上面所有数据源中
          # 初始化大小，最小，最大
          initialSize: 5
          minIdle: 1
          maxActive: 50
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: false
          #spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,log4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          # 合并多个DruidDataSource的监控数据
          #spring.datasource.useGlobalDataSourceStat=true
        db1:
          driver-class-name: net.sourceforge.jtds.jdbc.Driver
          url: jdbc:jtds:sqlserver://192.168.0.64:1433/hb_csms;useLOBs=false
          username: sa
          password: 12345678
          # 下面为连接池的补充设置，应用到上面所有数据源中
          # 初始化大小，最小，最大
          initialSize: 5
          minIdle: 1
          maxActive: 50
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: false
          #spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,log4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          # 合并多个DruidDataSource的监控数据
          #spring.datasource.useGlobalDataSourceStat=true
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/config/config.xml
  type-aliases-package: com.hb;com.hbsoft
hb:
  ###### 资源库名称
  resourcesName: hb_csms
  path: https://web.vfpbs.cn/
  dept: 401308
  loginRequired: false
  hbsoftKey: hbsoftkey123
  getLoginInfo: https://web.vfpbs.cn/thirdPartyLogin
  projectName: /
  taskFlag: false
  uploadPath: csms/
  loan_dept: 001
  loanBank: 463
  dingDing:
    #钉钉使用方式  1 自己钉钉  2 接口
    type: 1
    corpId: ding452b085346482a0f
    agentId: 716310219
    appKey: dingnct6r3hf04otj03p
    appSecret: MJBfz4MXmWy63FjxXtax8RsyqOVaen6vEmvRyVVgTknZAl2XdwuwqDj0-hCJ5lQa
    key: a17aba5bbacfa2a4c2f6d44f03c9c0fa
    ddUrl: http://ttdiis.czzrcb.com/dingding/czzrcb/ttd/websrv.asp
  dingMessage:
    picUrl: http://sq.vfpbs.com/csms/images/banner.png
    messageUrl: http://sq.vfpbs.com/csms/ddApplication


